export const REQUEST_CORPUSES = "REQUEST_CORPUSES";
export const CLEAR_CORPUSES = "CLEAR_CORPUSES";
export const REQUEST_CORPUSES_SUCCESS = "REQUEST_CORPUSES_SUCCESS";
export const REQUEST_CORPUSES_FAILURE = "REQUEST_CORPUSES_FAILURE";
export const SET_CORPUS_PAGE = "SET_CORPUS_PAGE";
export const SET_CORPUS_SEARCH_FILTER = "SET_CORPUS_SEARCH_FILTER";
export const SELECT_CORPUS = "SELECT_CORPUS";
export const UNSELECT_CORPUS = "UNSELECT_CORPUS";